name: appladmix
channels:
  - conda-forge
  - bioconda

dependencies:
  - python=3.6
  - admixtools
  - admixture
  - bcftools
  - bwa
  - eigensoft
  - nano
  - notebook
  - pandas
  - numpy
  - openjdk
  - plink
  - tabix
  - samtools  
  - bedtools
