name: appladmix
channels:
  - conda-forge
  - bioconda

dependencies:
  - r==4.1
  - nano
  - notebook
  - pandas
  - numpy
  - openjdk
  - tabix
  - samtools
  - bedtools
  - bcftools
  - bwa
  - plink
