name: appladmix
channels:
  - conda-forge
  - bioconda

dependencies:
  - r=4.1
  - nano
  - notebook
  - pandas
  - numpy
  - openjdk
  - tabix
  - samtools
  - bedtools
  - bcftools
  - bwa
  - plink
  - r-tidyverse
  - r-abind
  - r-cli
  - r-crayon
  - r-cubelyr
  - r-data.tree
  - r-digest
  - r-doParallel
  - r-dplyr
  - r-foreach
  - r-furrr
  - r-future
  - r-ggplot2
  - r-igraph
  - r-lobstr
  - r-magrittr
  - r-quadprog
  - r-purrr
  - r-Rcpp
  - r-RcppArmadillo
  - r-readr
  - r-rlang
  - r-stringi
  - r-stringr
  - r-tibble
  - r-tidyr
  - r-mgcv
  - r-MASS
  - r-rmarkdown
  