name: appladmix
channels:
  - conda-forge
  - bioconda
dependencies:
  - admixtools
  - admixture
  - bcftools
  - bwa
  - eigensoft
  - nano
  - notebook
  - numpy
  - openjdk
  - pandas
  - plink
  - tabix
  - samtools  
  - r-base=4 
  - r-ggplot2=3.3.2
  - r-rcpp
  - r-tidyverse
  - r-igraph
  - r-plotly
  - r-future
  - r-future.apply
  - r-furrr
  - r-remotes 
  - radian 
