name: appladmix
channels:
  - conda-forge
  - bioconda

dependencies:
  - r-4.1-2022-01-10
  - python-3.7
  - nano
  - notebook
  - pandas
  - numpy
  - openjdk
  - tabix
  - samtools
  - bedtools
  - bcftools
  - bwa
  - plink
  - abind
  - cli
  - crayon
  - cubelyr
  - data.tree
  - digest
  - doParallel
  - dplyr (>= 1.0.0)
  - foreach
  - furrr
  - future
  - ggplot2
  - grDevices
  - igraph (>= 1.3.5)
  - lobstr
  - magrittr
  - quadprog
  - purrr
  - Rcpp
  - RcppArmadillo
  - readr
  - rlang
  - stats
  - stringi
  - stringr
  - tibble
  - tidyr  (>= 1.0.0)
  - utils
  - mgcv
  - MASS