name: ineal
channels:
  - conda-forge
  - bioconda
dependencies:
  - admixtools
  - admixture
  - bcftools
  - clustalo
  - eigensoft
  - nano
  - notebook
  - numpy
  - openjdk
  - pandas
  - plink
  - raxml
  - tabix
